# To execute this docker-compose yml file use `docker-compose -f docker-compose-v2.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v2.yml down`

version: '3'
services:
  chrome:
    image: selenium/node-chrome:latest
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_RESOLUTION=1920x1080
    ports:
      - "6900:5900"


  
  novnc:
    image: dorowu/ubuntu-desktop-lxde-vnc
    links:
      - selenium-hub
    environment:
      - VNC_RESOLUTION=1920x1080

  selenium-hub:
    image: selenium/hub:4.1.0-prerelease-20211105
    build: .
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
      - "6900:5900"
      - "6901:5900"
      - "6902:5900"
      - "6080:80"
    shm_size: 2gb
    links:
      - chrome
   
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - DEBUG=true
      - VNC_RESOLUTION=1920x1080
